languageCode: "en"
title: ASP
paginate: 5
theme: PaperModX


enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: ""
  author:
    - Antonio Serrano
  mainSections:
    - articles  
    - resources
  disableAnchoredHeadings: false
  images: ["cover.png"]
  DateFormat: "2006-01-02"
  #useCustomAnalytics: true

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  ShowWordCount: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  TocOpen: true
  TocSide: "right"
  EnableInstantClick: true
  EnableImageZoom: true

  disqusShortname: aserpal

  editPost:
    URL: "https://github.com/reorx/hugo-PaperModX/tree/exampleSite/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # label:
  #     text: "Home"
  #     icon: icon.png
  #     iconHeight: 35

  # assets:
  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

minify:
  disableXML: true
  # minifyOutput: true

DefaultContentLanguage: "en"
defaultContentLanguageInSubdir: True

languages:
  en:
    baseURL: "/en/
    languageName: ":uk:"
    contentDir: "content/en"
    weight: 1
    title: ASP
    profileMode:
      enabled: true
      title: Antonio Serrano
      imageUrl: "profile.png"
      # imageTitle: my image
      # imageWidth: 120
      # imageHeight: 120
      subtitle: A Cybersecurity Learning Journey
    menu:
      main:
        - name: Articles
          url: /articles/
          weight: 1
        - name: Resources
          url: /resources/
          weight: 1
        - name: Categories
          url: /categories/
          weight: 4
        - name: Tags
          url: /tags/
          weight: 4
        - name: Archive
          url: /archives/
          weight: 5
        - name: Search
          url: /search/
          weight: 10
        - name: "About"
          url: "/about/"
  es:
    languageName: ":es:"
    languageAltTitle: "Español"
    contentDir: "content/es"
    weight: 2
    baseURL: "/es/"
    title: ASP
    profileMode:
      enabled: true
      title: Antonio Serrano
      imageUrl: "profile.png"
      # imageTitle: my image
      # imageWidth: 120
      # imageHeight: 120
      subtitle: Trayectoria de Aprendizaje en Ciberseguridad
    menu:
      main:
        - name: Artículos
          url: articles/
          weight: 1
        - name: Recursos
          url: resources/
          weight: 1
        - name: Categorías
          url: categories/
          weight: 4          
        - name: Etiquetas
          url: tags/
          weight: 5
        - name: Archivo
          url: archives/
        - name: Buscar
          url: search/
          weight: 10
        - name: "Sobre mí"
          url: about


outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  category: categories
  tag: tags
  series: series

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
    lineNos: false
    noClasses: false

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
